### ISSUE TITLE
Comma Plugin is incompatible with IntelliJ Community 2024.03

### ISSUE THREAD

**Issue by ikarpenis** [ab5tract/comma-plugin#18] opened 2024-11-14 08:33 UTC
![image](https://github.com/user-attachments/assets/70690ca8-5ff6-4e96-8be4-e237c37404f0)

**Comment by ikarpenis** [comment] 2024-11-14 08:59
![image](https://github.com/user-attachments/assets/79ec972d-29fc-4301-a09e-f1c756debcee)

**Comment by ab5tract** [comment] 2024-11-14 18:32
Unfortunately I only have the time to push a patch but not to test. If you have a moment please give `beta 28` a try and see if it resolves the issue.

Otherwise I will look at it further when later today.

**Comment by ikarpenis** [comment] 2024-11-15 06:10
With version **v2.0-beta.28-alpha.1** I get the same error message.

**Comment by librasteve** [comment] 2024-11-15 09:03
I just tried v2.0-beta.28-alpha.1 and got Plugin 'Comma for Raku' (version '2.0') is not compatible with the current version of the IDE, because it requires build 242.* or older but the current build is IU-243.21565.193

**Comment by ab5tract** [comment] 2024-11-18 19:42
This should be addressed in `[beta 29](https://github.com/ab5tract/comma-plugin/releases/tag/v2.0-beta.29)`.

However there are at least two regressions, and there may be more. I'll create tickets for the regressions I've seen, please create tickets for any others that you notice.

**Closed** 2024-11-18 20:03 UTC
