### ISSUE TITLE
Syntax Highlighting not working after comma-plugin 2.0 install

### ISSUE THREAD

**Issue by librasteve** [ab5tract/comma-plugin#4] opened 2024-09-22 14:19 UTC
Sonoma 14.6.1, M1
Welcome to Rakudo™ v2024.08
IntelliJ IDEA 2024.2.1 (Ultimate Edition)
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9

I have successfully performed the following:
- fork and clone comma-plugin
- open IntelliJ, build and runIde
- open (in selector window) existing raku project
- view lovely syntax highlighting in .rakumod file

However, this does not work:
- install and restart the newly built comma-plugin file (from build/distributions)
- open (in selector window) [same] existing raku project
- no syntax highlighting

Workarounds that do NOT fix this are:
- Invalidate Caches
- `rm -rf .idea && rm *.iml`
- New Project From Existing Sources

The following workarounds DO work:
- open the project in the runIde vm and then open again in the regular open dialog (selector window)
- right click unsyntaxed `.rakumod` file and Override File Type > Raku Module

I am OK to use the first path and expect this to be a one time thing for each project
Posting here to guide further improvements and to assist others with the workarounds

**Comment by ab5tract** [comment] 2024-09-22 15:16
Thanks for the report. I hope to make transitioning old projects as easy as possible, but it seems there are corner cases yet to be uncovered.

Can you try also `File > Invalidate Caches` ?

**Comment by librasteve** [comment] 2024-09-22 15:47
Just tried 
- `rm -rf .idea && rm *.iml`
- File > Open 

Still no syntax highlighting ;-(

**Comment by librasteve** [comment] 2024-09-22 21:09
OK, you asked me to provide an example GH repo where I was seeing this error.

I am testing with https://github.com/librasteve/raku-Physics-Unit.git

Previously (CommaIDE) I had included `.idea` etc project files in the GH commit.

I performed these steps:

- `rm -rf raku-Physics-Unit`
- `git clone https://github.com/librasteve/raku-Physics-Unit.git && cd raku-Physics-Unit`

NOW the IntelliJ File > Open works as desired

To inspect the changes, I then went:

`git status` 

and got 

```
GitWorld/raku-Physics-Unit > git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .idea/workspace.xml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.idea/comma.xml
```

I have committed and pushed the new idea files to GH so you can diff the changes.

---

However,  I have tried this pattern again this time re-clone eg raku-Physics-Measure and File > Open and syntax highlighting is not working.

So this issue is not

**Comment by ab5tract** [comment] 2024-09-24 10:29
Unfortunately I was unable to reproduce this issue. It opened with syntax highlighting each and every time.

That said, I did identify a misunderstanding I had with project setup that had been addressed in the new project wizard but not yet in the project open processor.

With any luck this fix will address the issue you are seeing.

**Closed** 2024-10-17 21:42 UTC
